version: "3.7"
services:
  api:
    restart: always
    build:
      context: .
      target: staging
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4200:4200
    command: node ./src/index.js